### ISSUE TITLE
bug dessin avant choix mot

### ISSUE THREAD

**Issue by Patroval** [Louis-Gv/Super-Sketch#10]
on peut dessiner avant de choisir le mot et sans cliquer
![image](https://user-images.githubusercontent.com/62056751/80834246-99fb0c00-8bf0-11ea-9fcc-9af3b20d079c.png)     je pense que ça arrive quand on reste appuyé sur le clic

**Comment by ElNeoX-dev** [comment]
Ouais j'ai fait une boulette
